<?php

// if( function_exists('acf_add_local_field_group') ):

//     acf_add_local_field_group(array(
//         'key' => 'group_6009e62d3f758',
//         'title' => 'Flitshop - Configurações',
//         'fields' => array(
//             array(
//                 'key' => 'field_600ae1c509d65',
//                 'label' => 'Geral',
//                 'name' => '',
//                 'type' => 'tab',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'placement' => 'top',
//                 'endpoint' => 0,
//             ),
//             array(
//                 'key' => 'field_600ae1db09d66',
//                 'label' => 'URL da Loja',
//                 'name' => 'flitshop_integration_url_loja',
//                 'type' => 'url',
//                 'instructions' => '',
//                 'required' => 1,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//             ),
//             array(
//                 'key' => 'field_600ae1ff09d67',
//                 'label' => 'API Token',
//                 'name' => 'flitshop_integration_api_token',
//                 'type' => 'textarea',
//                 'instructions' => '',
//                 'required' => 1,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'maxlength' => '',
//                 'rows' => '',
//                 'new_lines' => '',
//             ),
//             array(
//                 'key' => 'field_60565cdd3af16',
//                 'label' => 'Conversões',
//                 'name' => '',
//                 'type' => 'tab',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'placement' => 'top',
//                 'endpoint' => 0,
//             ),
//             array(
//                 'key' => 'field_60565cfd3af17',
//                 'label' => '',
//                 'name' => '',
//                 'type' => 'message',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'message' => 'Escolha quais tipos de evento devem ser considerados como conversão.',
//                 'new_lines' => 'wpautop',
//                 'esc_html' => 0,
//             ),
//             array(
//                 'key' => 'field_60565d5c3af19',
//                 'label' => 'Boleto Gerado',
//                 'name' => 'flitshop_integration_ticket_created',
//                 'type' => 'true_false',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '25',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'message' => '',
//                 'default_value' => 1,
//                 'ui' => 1,
//                 'ui_on_text' => '',
//                 'ui_off_text' => '',
//             ),
//             array(
//                 'key' => 'field_60565d473af18',
//                 'label' => 'Cartão Aprovado',
//                 'name' => 'flitshop_integration_credit_card_success',
//                 'type' => 'true_false',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '25',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'message' => '',
//                 'default_value' => 1,
//                 'ui' => 1,
//                 'ui_on_text' => '',
//                 'ui_off_text' => '',
//             ),
//             array(
//                 'key' => 'field_60565a5ad6a93',
//                 'label' => 'Cartão em Análise',
//                 'name' => 'flitshop_integration_credit_card_pending',
//                 'type' => 'true_false',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '25',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'message' => '',
//                 'default_value' => 1,
//                 'ui' => 1,
//                 'ui_on_text' => '',
//                 'ui_off_text' => '',
//             ),
//             array(
//                 'key' => 'field_60565d7c3af1a',
//                 'label' => 'Cartão Cancelado',
//                 'name' => 'flitshop_integration_credit_card_canceled',
//                 'type' => 'true_false',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '25',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'message' => '',
//                 'default_value' => 0,
//                 'ui' => 1,
//                 'ui_on_text' => '',
//                 'ui_off_text' => '',
//             ),
//             array(
//                 'key' => 'field_60686f3ea8d6b',
//                 'label' => 'Facebook Pixel',
//                 'name' => '',
//                 'type' => 'group',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'layout' => 'block',
//                 'sub_fields' => array(
//                 ),
//             ),
//             array(
//                 'key' => 'field_60686f52daf4a',
//                 'label' => 'Facebook Pixel ID',
//                 'name' => 'flitshop_integration_pixel_id',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_60686f25a8d6a',
//                 'label' => 'Facebook Pixel Access Token',
//                 'name' => 'flitshop_integration_pixel_access_token',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_60687e722ef4f',
//                 'label' => 'Conversão Cartão de Crédito',
//                 'name' => 'flitshop_integration_conversion_credit_card',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '33',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_60687ea72ef50',
//                 'label' => 'Conversão Boleto Gerado',
//                 'name' => 'flitshop_integration_conversion_ticket_created',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '33',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_60687f354cb01',
//                 'label' => 'Conversão Pix',
//                 'name' => 'flitshop_integration_conversion_pix',
//                 'type' => 'text',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '33',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'maxlength' => '',
//             ),
//             array(
//                 'key' => 'field_600ae1b109d64',
//                 'label' => 'Redirecionamentos',
//                 'name' => '',
//                 'type' => 'tab',
//                 'instructions' => '',
//                 'required' => 0,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'placement' => 'top',
//                 'endpoint' => 0,
//             ),
//             array(
//                 'key' => 'field_600b319b4343d',
//                 'label' => 'Fallback	Redirect',
//                 'name' => 'flitshop_integration_fallback_redirect',
//                 'type' => 'url',
//                 'instructions' => 'Deixe em branco para redirecionar para a página padrão do Flitshop.',
//                 'required' => 1,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//             ),
//             array(
//                 'key' => 'field_60469cfd84034',
//                 'label' => 'Pending Redirect',
//                 'name' => 'flitshop_integration_pending_redirect',
//                 'type' => 'url',
//                 'instructions' => '',
//                 'required' => 1,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//             ),
//             array(
//                 'key' => 'field_60475055bb33b',
//                 'label' => 'Canceled Redirect',
//                 'name' => 'flitshop_integration_canceled_redirect',
//                 'type' => 'url',
//                 'instructions' => '',
//                 'required' => 1,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'default_value' => '',
//                 'placeholder' => '',
//             ),
//             array(
//                 'key' => 'field_6009e64624f5a',
//                 'label' => 'Redirecionamentos',
//                 'name' => 'flitshop_integration_redirects',
//                 'type' => 'repeater',
//                 'instructions' => '',
//                 'required' => 1,
//                 'conditional_logic' => 0,
//                 'wrapper' => array(
//                     'width' => '',
//                     'class' => '',
//                     'id' => '',
//                 ),
//                 'collapsed' => 'field_6009f1da24f5f',
//                 'min' => 0,
//                 'max' => 0,
//                 'layout' => 'block',
//                 'button_label' => 'Adicionar redirecionamento',
//                 'sub_fields' => array(
//                     array(
//                         'key' => 'field_6009f1da24f5f',
//                         'label' => 'Nome da Condição',
//                         'name' => 'name',
//                         'type' => 'text',
//                         'instructions' => '',
//                         'required' => 1,
//                         'conditional_logic' => 0,
//                         'wrapper' => array(
//                             'width' => '33',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'default_value' => '',
//                         'placeholder' => '',
//                         'prepend' => '',
//                         'append' => '',
//                         'maxlength' => '',
//                     ),
//                     array(
//                         'key' => 'field_600f1dcdaf77d',
//                         'label' => 'Equivalente Teste AB',
//                         'name' => 'ab_variant',
//                         'type' => 'page_link',
//                         'instructions' => '',
//                         'required' => 1,
//                         'conditional_logic' => 0,
//                         'wrapper' => array(
//                             'width' => '',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'post_type' => array(
//                             0 => 'flit-thanks-redirect',
//                         ),
//                         'taxonomy' => '',
//                         'allow_null' => 0,
//                         'allow_archives' => 0,
//                         'multiple' => 0,
//                     ),
//                     array(
//                         'key' => 'field_600fdf55f61ca',
//                         'label' => 'Redirecionar para...',
//                         'name' => 'redirect_type',
//                         'type' => 'select',
//                         'instructions' => '',
//                         'required' => 1,
//                         'conditional_logic' => 0,
//                         'wrapper' => array(
//                             'width' => '',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'choices' => array(
//                             'flitshop' => 'Página de Agradecimento Flitshop',
//                             'redirect_to_wp' => 'Selecionar página WP',
//                             'redirect_to_url' => 'URL Personalizada',
//                         ),
//                         'default_value' => 'flitshop',
//                         'allow_null' => 0,
//                         'multiple' => 0,
//                         'ui' => 0,
//                         'return_format' => 'value',
//                         'ajax' => 0,
//                         'placeholder' => '',
//                     ),
//                     array(
//                         'key' => 'field_6009f4917a161',
//                         'label' => 'Página WP',
//                         'name' => 'redirect_to_wp',
//                         'type' => 'page_link',
//                         'instructions' => '',
//                         'required' => 1,
//                         'conditional_logic' => array(
//                             array(
//                                 array(
//                                     'field' => 'field_600fdf55f61ca',
//                                     'operator' => '==',
//                                     'value' => 'redirect_to_wp',
//                                 ),
//                             ),
//                         ),
//                         'wrapper' => array(
//                             'width' => '',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'post_type' => '',
//                         'taxonomy' => '',
//                         'allow_null' => 0,
//                         'allow_archives' => 0,
//                         'multiple' => 0,
//                     ),
//                     array(
//                         'key' => 'field_600fdfe3f61cb',
//                         'label' => 'URL Personalizada',
//                         'name' => 'redirect_to_url',
//                         'type' => 'url',
//                         'instructions' => '',
//                         'required' => 1,
//                         'conditional_logic' => array(
//                             array(
//                                 array(
//                                     'field' => 'field_600fdf55f61ca',
//                                     'operator' => '==',
//                                     'value' => 'redirect_to_url',
//                                 ),
//                             ),
//                         ),
//                         'wrapper' => array(
//                             'width' => '',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'default_value' => '',
//                         'placeholder' => '',
//                     ),
//                     array(
//                         'key' => 'field_60114c31e2314',
//                         'label' => 'Produtos',
//                         'name' => 'products',
//                         'type' => 'taxonomy',
//                         'instructions' => 'Deixe em branco para aplicar a TODOS os produtos.',
//                         'required' => 0,
//                         'conditional_logic' => 0,
//                         'wrapper' => array(
//                             'width' => '',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'taxonomy' => 'produtos',
//                         'field_type' => 'multi_select',
//                         'allow_null' => 1,
//                         'add_term' => 1,
//                         'save_terms' => 1,
//                         'load_terms' => 0,
//                         'return_format' => 'object',
//                         'multiple' => 0,
//                     ),
//                     array(
//                         'key' => 'field_60114c8fe2315',
//                         'label' => 'Método de Pagamento',
//                         'name' => 'methods',
//                         'type' => 'taxonomy',
//                         'instructions' => 'Deixe em branco para aplicar a TODOS os produtos.',
//                         'required' => 0,
//                         'conditional_logic' => 0,
//                         'wrapper' => array(
//                             'width' => '',
//                             'class' => '',
//                             'id' => '',
//                         ),
//                         'taxonomy' => 'methods',
//                         'field_type' => 'multi_select',
//                         'allow_null' => 1,
//                         'add_term' => 1,
//                         'save_terms' => 1,
//                         'load_terms' => 0,
//                         'return_format' => 'object',
//                         'multiple' => 0,
//                     ),
//                 ),
//             ),
//         ),
//         'location' => array(
//             array(
//                 array(
//                     'param' => 'options_page',
//                     'operator' => '==',
//                     'value' => 'flitshop-int-configs',
//                 ),
//             ),
//         ),
//         'menu_order' => 0,
//         'position' => 'normal',
//         'style' => 'default',
//         'label_placement' => 'top',
//         'instruction_placement' => 'label',
//         'hide_on_screen' => '',
//         'active' => true,
//         'description' => '',
//     ));
    
//     endif;